apiVersion: 1

datasources:
  - name: HAK-GAL Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:8000
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 5s
