# Prometheus configuration for HAK/GAL Performance Optimizer
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # HAK/GAL Performance Optimizer metrics
  - job_name: 'hakgal-performance-optimizer'
    static_configs:
      - targets: ['hakgal-app:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # System metrics (if node_exporter is available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093