apiVersion: apps/v1
kind: Deployment
metadata:
  name: hakgal-performance-optimizer-staging
  namespace: hakgal-staging
  labels:
    app: hakgal-performance-optimizer
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hakgal-performance-optimizer
      environment: staging
  template:
    metadata:
      labels:
        app: hakgal-performance-optimizer
        environment: staging
    spec:
      containers:
      - name: hakgal-performance-optimizer
        image: hakgal/performance-optimizer:latest
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8000
          name: metrics
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "INFO"
        - name: DATABASE_PATH
          value: "/data/hakgal.db"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: hakgal-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hakgal-performance-optimizer-staging-service
  namespace: hakgal-staging
  labels:
    app: hakgal-performance-optimizer
    environment: staging
spec:
  selector:
    app: hakgal-performance-optimizer
    environment: staging
  ports:
  - name: http
    port: 80
    targetPort: 5000
  - name: metrics
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hakgal-data-pvc
  namespace: hakgal-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi